version: "3.3"

services:
  traefik:
    image: "traefik:latest"
    command:
      - --log.level=INFO
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.postgres-master.address=:5432
      - --providers.docker=true
      - --providers.swarm.exposedbydefault=false
      - --providers.swarm.endpoint=unix:///var/run/docker.sock
      - --providers.swarm.network=traefik-public
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --api
      - --api.dashboard=true
      - --certificatesresolvers.leresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.leresolver.acme.email=support@coastalsites.dev
      - --certificatesresolvers.leresolver.acme.storage=/le/acme.json
      - --certificatesresolvers.leresolver.acme.tlschallenge=true
    ports:
      - "80:80"
      - "443:443"
      - "5432:5432"
    networks:
      - app-internal
      - traefik-public
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/mnt/data/traefik/acme.json:/le/acme.json"
      - "/mnt/data/traefik/dynamic:/etc/traefik/dynamic"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.coastalsites.dev`)"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        - "traefik.http.routers.traefik.tls.certresolver=leresolver"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.middlewares=authtraefik"
        - "traefik.http.middlewares.authtraefik.basicauth.users=admin:$$2y$$05$$xW72ue5zc3kabA1k//hn1ut7xMCX6Zdw6hHKpmIRqKsJWsJqJFSCa"

networks:
  traefik-public:
    external: true
  app-internal:
    external: true