version: "3.3"

services:
  traefik:
    image: "traefik:latest"
    command:
      - --log.level=INFO
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.swarm.exposedbydefault=false
      - --providers.swarm.endpoint=unix:///var/run/docker.sock
      - --providers.swarm.network=traefik-public
      - --api
      - --api.dashboard=true
      - --certificatesresolvers.leresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      # update your email here
      - --certificatesresolvers.leresolver.acme.email=support@coastalsites.dev
      # Make sure the this file is available and permission is set correctly
      - --certificatesresolvers.leresolver.acme.storage=/le/acme.json
      - --certificatesresolvers.leresolver.acme.tlschallenge=true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik-public
    providers:
      file:
        directory: /etc/traefik/dynamic
        watch: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # Make sure the volume folder is created
      - "/mnt/data/traefik/acme.json:/le/acme.json"
      - "/mnt/data/traefik/dynamic:/etc/traefik/dynamic"
    deploy:
      labels:
        # Dashboard
        - "traefik.enable=true"
        # Change the host url here
        - "traefik.providers.file.directory.directory=/etc/traefik/dynamic"
        - "traefik.providers.file.directory.watch=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.coastalsites.dev`)"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        - "traefik.http.routers.traefik.tls.certresolver=leresolver"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.middlewares=authtraefik"
        # Change the auth password here
        - "traefik.http.middlewares.authtraefik.basicauth.users=admin:$$2y$$05$$xW72ue5zc3kabA1k//hn1ut7xMCX6Zdw6hHKpmIRqKsJWsJqJFSCa" # user/password

        # global redirect to https
        - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
        - "traefik.http.routers.http-catchall.entrypoints=web"
        - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

        # middlewares
        #redirect
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        # rate limits in seconds
        - "traefik.http.middlewares.test-ratelimit.ratelimit.average=100"
        - "traefik.http.middlewares.test-ratelimit.ratelimit.burst=200"

networks:
  traefik-public:
    external: true